### ISSUE TITLE
Redirect uri?

### ISSUE THREAD

**Issue by gumdum** [long1eu/google_sign_in_dart#3]
Is there a place to set the redirect uri? It's actually popping up on my desktop, but using FirebaseAuth, it is returning a 'Error 400: redirect_uri_mismatch' error that the request uri is not present. Of course the request uri changes on desktop version it appears: 127.0.0.1:xxx the port constantly changes, so it cant be set in the Oauth panel of google.

flutter: PlatformException(failed_to_recover_auth, <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>
, null, null)

**Comment by long1eu** [comment]
Good point. Can you create a pull request?

**Comment by ozozozd** [comment]
I tested the example and it somehow successfully redirects to 127.0.0.1 with random ports.

@long1eu can you share how you set up your Google OAuth to allow that?

**Comment by long1eu** [comment]
@ozozozd have a look at the example folder

**Comment by ozozozd** [comment]
Just submitted a PR for the port parameter.
https://github.com/long1eu/google_sign_in_dart/pull/5/files

Although I still have no idea how the example works without a fixed port.
